# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jillian Etheredge
tagline:          'An Exploration of Data Science'
description:      'A blog dedicated to my exploration of data science concepts from my time at Metis and beyond'
url:              http://Jilliane1993.github.io
baseurl:          /

author:
  name:           'Jillian Etheredge'
  url:            https://www.linkedin.com/in/jillian-etheredge-357127163/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Jilliane1993
